apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-appfor-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/firassBenNacib/appfor-helm.git'
    path: helm
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
