apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "myapp.fullname" . }}-scaledobject
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "myapp.fullname" . }}
  pollingInterval: {{ .Values.scaling.pollingInterval }}
  cooldownPeriod: {{ .Values.scaling.cooldownPeriod }}
  minReplicaCount: {{ .Values.scaling.minReplicaCount }}
  maxReplicaCount: {{ .Values.scaling.maxReplicaCount }}
  triggers:
    - type: prometheus
      metadata:
        serverAddress: {{ .Values.prometheus.serverAddress }}
        metricName: '{{ index .Values.scaling.prometheusTriggers 0 "metricName" }}'
        query: '{{ index .Values.scaling.prometheusTriggers 0 "query" }}'
        threshold: '{{ index .Values.scaling.prometheusTriggers 0 "threshold" }}'
        cooldownPeriod: '{{ index .Values.scaling.prometheusTriggers 0 "cooldownPeriod" }}'
    - type: activemq
      metadata:
        managementEndpoint: {{ .Values.activemq.managementEndpoint }}
        destinationName: '{{ index .Values.scaling.activemqTriggers 0 "destinationName" }}'
        brokerName: '{{ index .Values.scaling.activemqTriggers 0 "brokerName" }}'
        targetQueueSize: '{{ index .Values.scaling.activemqTriggers 0 "targetQueueSize" }}'  
        activationTargetQueueSize: '{{ index .Values.scaling.activemqTriggers 0 "activationTargetQueueSize" }}'  
        cooldownPeriod: '{{ index .Values.scaling.activemqTriggers 0 "cooldownPeriod" }}'   
        username: '{{ index .Values.scaling.activemqTriggers 0 "username" }}'
        password: '{{ index .Values.scaling.activemqTriggers 0 "password" }}'