apiVersion: v1
kind: Service
metadata:
  name: {{ include "myapp.fullname" . }}-service
  labels:
    app: myapp
spec:
  type: {{ .Values.service.type }}
  selector:
    app: myapp
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8082
