image:
  repository: firaskill12/kube-keda
  tag: 427

volume:
  mountPath: /app/data
  hostPath: /run/desktop/mnt/host/c/Users/MSI/OneDrive/Bureau/message_datasets

service:
  type: ClusterIP
  port: 8082

prometheus:
  serverAddress: http://10.110.96.5:9090

activemq:
  managementEndpoint: "activemq-service:8161"

scaling:
  pollingInterval: 5
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 10
  prometheusTriggers:
    - type: prometheus
      metricName: active_processing_messages
      query: sum(active_processing_messages)
      threshold: '1'
      cooldownPeriod: '10'
  activemqTriggers:
    - type: activemq
      destinationName: "message Queue"
      brokerName: "localhost"
      targetQueueSize: "100000"  
      activationTargetQueueSize: "1000"  
      cooldownPeriod: "10"   
      username: "admin"
      password: "admin"  
  